### ISSUE TITLE
Relevant Pixels Visualization

### ISSUE THREAD

**Issue by aleflabo** [nupurkmr9/S2M2_fewshot#10]
Hi,

I'm trying to reproduce the Figure 5 of the paper where are shown the most relevant pixels for the classification.
I kindly ask you how they were generated and if the the code is available to replicate them.

Thanks in advance,
Alessandro

**Comment by nupurkmr9** [comment]
Hi, Sorry I dont have the exact code available now. But, we create Fig5 by highlighting 1% of the pixels sorted by abs(dy/dx) where x is the input image and y is the correct class. I hope this helps. 

Thanks,
Nupur
