### ISSUE TITLE
Fail to open the model for tiredImagenet because it is only 140MB

### ISSUE THREAD

**Issue by allenhaozhu** [nupurkmr9/S2M2_fewshot#12]
Nice to see you release the model of S2M2 but there is one broken and only 140MB. But other models are 380+MB, would you mind update that?

**Comment by nupurkmr9** [comment]
Hi, tieredImageNet model is only 140MB because it is only the final S2M2 model, whereas for other datasets we released models corresponding to all three variants discussed in our paper i.e. rotation, manifold-mixup and S2M2. 

Let me know if you face any other issues in using the model.
