### ISSUE TITLE
How to reproduce your result?

### ISSUE THREAD

**Issue by ljjcoder** [nupurkmr9/S2M2_fewshot#13]
Thanks for your work! I want to reproduce the results of Rolation. 
I followed your request for three steps.
First：
python train.py --dataset miniImagenet --method rotation --model WideResNet28_10 --stop_epoch 200 --batch_size 64 --test_batch_size 16
second：
python save_features.py --dataset miniImagenet --method rotation --model WideResNet28_10
Third：
python test.py --dataset miniImagenet --method rotation --model WideResNet28_10 --n_shot 1
However, I only got an accuracy of 0.56, while your paper has an accuracy of 0.639. Are there key steps missing in my training process?

**Comment by nupurkmr9** [comment]
Hi, 
Sorry for not mentioning in the repo, but the miniImagenet model was trained for 400 epochs. 
Thanks for pointing this out, I will update the repo with scripts for replicating results for all datasets. 
Let us know if you are able to replicate the results for rotation now.
