### ISSUE TITLE
link for pretrained model 

### ISSUE THREAD

**Issue by Yelysavite** [nupurkmr9/S2M2_fewshot#14]
Thank you for your work.
I've tried all the previous links。
I got a _pickle. unpicklingError when loading the pre-trained model while running train.py.
I would like to ask if you can post a link to pretrained model.
Thank you in advance.

**Comment by nupurkmr9** [comment]
Hi, is this because of python version? I am able to load the models using python3.8 and it should work on python3.7 as well. 
Can you try  on Python3.8?

**Comment by ucasligang** [comment]
No, it's your file had broken.

**Comment by nupurkmr9** [comment]
Can you tell which model are you trying in torch.load()?

**Comment by ucasligang** [comment]
Sorry, I didn't check it carefully.
