### ISSUE TITLE
Fail to untar the model for tiredImagenet

### ISSUE THREAD

**Issue by ucasligang** [nupurkmr9/S2M2_fewshot#15]
Thanks for your promising work. There is an issue, I fail to untar the model for tiredImagenet because of the file is broken. Could you check it out, please?

**Comment by nupurkmr9** [comment]
For the tieredImagenet model untar is not required. You should be able to directly do torch.load(). 
Can you check that.

**Comment by ucasligang** [comment]
Thank you for you response. I have another little problem, the pretrained tieredImagenet model is first train a model with rotation self-supervision and finetune the model using both manifold mixup and rotation self-supervision, isn't it ?

**Comment by ucasligang** [comment]
If I only use the pretrained tieredImagenet model to extract the feature of tieredImagenet, I didn't need to fine-tune, is right?

**Comment by nupurkmr9** [comment]
yes, the model is trained by S2M2 training technique.

**Comment by ucasligang** [comment]
Thank you very much, we'll cite your article if our work gets published.
