### ISSUE TITLE
How to prepare dataset for tiredImagenet

### ISSUE THREAD

**Issue by YounkHo** [nupurkmr9/S2M2_fewshot#16]
Hello! Thanks for this incredible contribution.

I want to know how to train on tired-imagenet, I've downloaded tired-imagenet from [here](https://github.com/renmengye/few-shot-ssl-public), but the format is pkl and no train/vaild provided.

**Comment by nupurkmr9** [comment]
Hi, you can find the split at 
https://github.com/renmengye/few-shot-ssl-public/tree/master/fewshot/data/tiered_imagenet_split

Hope this helps :)

**Comment by YounkHo** [comment]
I've already downloaded this in fact and how should I use it to train a model? As what I do as mini-ImageNet?

**Comment by karayzhou** [comment]
hello, thanks for your great works, i want to know some training processes about the tieredImageNet pretrain model. 
How long has your model been trained in tieimagenet，and how many gpus were used，can you give some details, thank you

**Comment by nupurkmr9** [comment]
Hi @Dreamcreationman, Sorry for the late reply. 
I added tieredImageNet later on in the repo and I do not have the script similar to make_json.py saved now. But you can probably write a script to create the json with 'image_names' and 'image_labels' for tieredImageNet based on the train, val split provided on the above repo. I will try to add the script in the repo as well.

@karayzhou, we trained tieredImageNet for 100 epochs with rotation self-supervision and then fine-tuned with manifold-mixup for another 100 epochs. It was trained with other hyper-params same as miniImageNet i.e. batch-size 64. I don't remember which GPU we used, but I guess something like 4 V100 GPUs should probably be enough for training.

**Comment by karayzhou** [comment]
Thank you 😄

nupurkmr9 ***@***.***> 于2021年6月1日周二 下午11:00写道：
