### ISSUE TITLE
can't find computation of the exemplar loss in the code

### ISSUE THREAD

**Issue by sherrijj** [nupurkmr9/S2M2_fewshot#17]
Hi, I’m @sherrijj
   I’m interested in your project and code. But I can not find in your code how to compute the exemplar loss Le (in the paper). Is Le the same as Lrot ? Look forward your reply. Thanks.

**Comment by nupurkmr9** [comment]
Hi sherrijj, 
the current code does not contain the exemplar loss calculation, since the rotation self-supervision worked better than exemplar loss. 
If you have any doubts regarding the loss calculation, please let us know.

**Comment by sherrijj** [comment]
got it, thanks !
