### ISSUE TITLE
Mapping between Class-ID and Class Names

### ISSUE THREAD

**Issue by AutoVision-cloud** [nupurkmr9/S2M2_fewshot#19]
Hi, 
Thanks for this wonderful work.
Can you please let me know the mapping between class_id for test set, like [80, 81, 82..., 99] to class names like [hourglass, crate, malamute....]?

**Comment by nupurkmr9** [comment]
Hi, you can get the mapping of class number to ImageNet folder names for mini-ImageNet at https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet
