### ISSUE TITLE
Difference between checkpoints of S2M2_R and manifold mixup

### ISSUE THREAD

**Issue by chmxu** [nupurkmr9/S2M2_fewshot#22]
It seems that the models trained with manifold mixup and S2M2_R share the same structure and all weights contained in the mixup checkpoint should be also contained in the S2M2_R one. It is weird that the weight of the last linear layer (linear.L.weight_v and linear.L.weight_g) is missing in the provided WideResNet28_10_S2M2_R checkpoint for miniImagenet. Both of my trained version and the published one for tieredImagenet have those weights. I wonder if I have omitted any detail in the code and hope you can help me on that.

**Comment by nupurkmr9** [comment]
Hi, you are right about model structure being the same. It is possible that during some post-processing for modifying state_dict keys from a previous version of code to this, linear layer was ignored for miniImageNet. Probably because the last linear layer is not used in the final evaluation.

**Comment by chmxu** [comment]
Thank you!
