### ISSUE TITLE
Is the Pre training model on the tiered-Imagenet dataset in the online disk the final?

### ISSUE THREAD

**Issue by kevin-xiaoxin** [nupurkmr9/S2M2_fewshot#25]
First of all, thank you very much for your work. But when I ran the experiment, I encountered some problems. I hope you can help me. 
      I downloaded the Pre-training model on the tiered-Imagenet from the Google online disk you gave and used it to save the feature of the novel class.  Then I test it used the feature by save features.py. But my final result is much worse than that your report in the paper. My result on 1-shot is 68 and that on 5-shot is 85. Can you tell me what the problem is？ Or you can put the features of tiered-Imagenet in the online disk, and then I download them to continue my research.
     Thank you very much! @nupurkmr9 @msingh27 @Puneet2000

**Comment by PeizhengWang** [comment]
Hi, I encontered the same problem, and got similar result with you @llg123123. The test results of S2M2 in tieredImagenet are consistent with Manifold Mixup. Have you uploaded the wrong model? @nupurkmr9 
Thank you very much!

**Comment by safeAMI** [comment]
Hi, I encontered the same problem.I can't reproduce the result for tieredImageNet based on the pre-training model from Google online disk.

**Comment by safeAMI** [comment]
do you solve this?@kevin-xiaoxin
