### ISSUE TITLE
Missing file in download_miniImagenet.sh

### ISSUE THREAD

**Issue by vkverma01** [nupurkmr9/S2M2_fewshot#3]
download_miniImagenet.sh requires the following file that is missing:

python write_miniImagenet_filelist.py 
python write_cross_filelist.py

**Comment by nupurkmr9** [comment]
Hi, thanks for pointing it out. I have updated the filename in download_miniImagenet.sh. We don't use write_cross_filelist.py which is used for cross-domain training. For more reference on that please have a look at https://github.com/wyharveychen/CloserLookFewShot on which our code-base is built.
