### ISSUE TITLE
Did you use 80*80 images for mini-Imagenet dataset?

### ISSUE THREAD

**Issue by hyoje42** [nupurkmr9/S2M2_fewshot#4]
Hi. Thanks for sharing your code. Your paper and code help a lot for me. I have some questions.

1. Did you use 80*80 images for mini-Imagenet dataset?
I read your code, so I thought you used 80*80 cropped image for mini-Imagenet, but I want to clarify it. 
From the issue at 'A Closer Look At Fewshot', Chen, 
https://github.com/wyharveychen/CloserLookFewShot/issues/20
I think that Chen used 224*224 images for experiments that use Resnet as backbone. (I thought it is unfair to other papers, because original mini-Imagenet dataset consists of 84*84 images. If I were wrong, please correct me)

2. Where can you get the results on CIFAR dataset over Baseline++ with WRN-28-10 as backbone?
Chen did not use WRN-28-10 and CIFAR dataset, as far as I know. Did you get the results by yourself? Also I found that the reported accuracy little bit different from Chen's results.
For the mini-Imagenet dataset(5shot-5way), 76.16+-0.63 from Chen, but 74.14+-0.19 from yours. In your paper, did you get baseline++'s results by yourself?

Thanks, in advance.

**Comment by nupurkmr9** [comment]
Hi,
1. Yes, we use 80x80 crop from 84*84 resized images for mini-Imagenet as is recommended in previous literature. 
2. We ran baseline++ method by ourselves on all datasets including CIFAR. 

Thanks

**Comment by zwd973** [comment]
When I use ResNet18 as the backbone with a 80x80 input,  it produce a error:
![image](https://user-images.githubusercontent.com/34183018/143406669-013da2dc-6596-44cf-b11c-ba1c34e2bb05.png)

it seems the code is not correct, so how to reproduce your result when taking as input a 80x80 image but 224x224? @nupurkmr9

**Comment by Dracula-funny** [comment]
> When I use ResNet18 as the backbone with a 80x80 input, it produce a error: ![image](https://user-images.githubusercontent.com/34183018/143406669-013da2dc-6596-44cf-b11c-ba1c34e2bb05.png)
> 
> it seems the code is not correct, so how to reproduce your result when taking as input a 80x80 image but 224x224? @nupurkmr9

Have you solved this problem?

**Comment by hyoje42** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2024-03-28T23:26:54
          
          
            * Subject : 
Re: [nupurkmr9/S2M2_fewshot] Did you use 80*80 images for mini-Imagenet dataset? (#4)
          
          
            
              
                * Remote host said : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
