### ISSUE TITLE
Cannot reproduce S2M2_R

### ISSUE THREAD

**Issue by voa18105** [nupurkmr9/S2M2_fewshot#5]
Good day!
Is there a description how to reproduce your state-of-art results? I've tried to repeat your result with 1-shot S2M2_R on CUB, and got only 71%, should be 10% higher... 
I could describe what exactly did I do, but may be it would be more useful for me and everyone if you could describe what did you do?
Launch params, choosing epoch or smth else, do not know, but 10% lower means smth is wrong with my reproduce.

Thank you in advance!

**Comment by nupurkmr9** [comment]
Hi,
We first train a model with rotation self-sueprvision with the following hyper-parameters for CUB dataset: 
python train.py --dataset CUB --method rotation --model WideResNet28_10 --stop_epoch 200 --batch_size 64 --test_batch_size 16

We then finetune the model using both manifold mixup and rotation self-supervision using the command: 
python train.py --dataset CUB --method S2M2_R --model WideResNet28_10 --stop_epoch 100 --batch_size 64 --test_batch_size 16

Let us know if you still face any issues. 
Thanks.

**Comment by voa18105** [comment]
Thank you for instruction! I will follow it
