### ISSUE TITLE
Image size for Renset18 on CUB dataset

### ISSUE THREAD

**Issue by munjalbharti** [nupurkmr9/S2M2_fewshot#8]
Hi,
Can you please tell which image size you used for CUB dataset for Resnet18 ? 
The code from "A Closer Look At Fewshot" uses 224X224.
Did you use 80X80? 

I have this doubt because the results of Baseline++ are similar for your work and Chen's work. I wonder if the image size used is same or different?

Chen's work => 67.02 (1 shot), 83.58 (5 shot)
Your work => 67.68 (1 shot), 82.26 (5 shot)

Regards
Bharti

**Comment by nupurkmr9** [comment]
Hi,

We used 80x80 crop from 84x84 image size during training in keeping with several previous works (original mini-imagenet paper also uses 84x84 image size). We found a similar performance to "A Closer Look At Fewshot" paper which uses 224x224 on the CUB dataset.

**Comment by munjalbharti** [comment]
hi, 
Thank you for your reply. but the code does not work for Resnet18 with image size 80. Attached is the error message.

The issue is with the average pooling. The feature size before pooling is 512X3X3 for image size 80 (Resnet18) but the 7X7 pooling is being applied in the code.  

Did you also change the pooling size to 3 instead of 7 for image size 80 (Resnet18 model)? The pooling 7X7 works for image size 256.  


Regards
Bharti 


![Screen Shot 2020-12-13 at 12 03 44](https://user-images.githubusercontent.com/12259358/102010052-c0af2280-3d3b-11eb-98cd-160ca3bd659b.png)

**Comment by Dracula-funny** [comment]
> Hi, Thank you for your reply, but the code does not work for Resnet18 with image size 80. Attached is the error message.
> 
> The issue is with the average pooling. The feature size before pooling is 512X3X3 for image size 80 (Resnet18) but the 7X7 pooling is being applied in the code.
> 
> Did you also change the pooling size to 3 instead of 7 for image size 80 (Resnet18 model)? The pooling 7X7 works for image size 256.
> 
> Regards Bharti
> 
> ![Screen Shot 2020-12-13 at 12 03 44](https://user-images.githubusercontent.com/12259358/102010052-c0af2280-3d3b-11eb-98cd-160ca3bd659b.png)

Have you solved this problem?
